version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'    
    environment:       
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
